.\" $Id$
.\"
.\" Copyright (c) 2022 Michael Graves
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate$
.Dt MINIURL 1
.Os
.Sh NAME
.Nm miniurl
.Nd CGI program that will redirect client based on minified URL
.Sh SYNOPSIS
.Nm miniurl
.Sh DESCRIPTION
The
.Nm
CGI program utilized a SQL database to lookup a minified URL and then redirects
the calling system to the full URL.
.Pp
.Nm
should be accessed via a http servers CGI environment as a simple CGI
program.
.Sh ENVIRONMENT
Options can be passed in the environment to the
.Nm
program.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It COOKIE_TIMEOUT
The amount of idle time to keep the admin cookie valid. Default 1800 seconds.
.It COOKIE_NNAME
The name of the cookie. Default is 'url_authz'
.It DEBUG
Enable additional debug logging of the CGI program.  These logs will be sent to
the errors.log file of the http server. To enable set the value to "1"

